version: '3'

services:
  rabbit:
    image: rabbitmq:latest
    hostname: rabbit
    container_name: "rabbitmq"
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=123456
    volumes:
      - ${DOCKER_WORKDIR}/rabbitmq/data:/var/lib/rabbitmq
