version: '3'

services: 
  redis:
    image: redis:latest
    container_name: "redis"
    restart: always
    ports:
      - 6379:6379
    volumes: 
      - ${DOCKER_WORKDIR}/reids/data:/data
    # command: redis-server --appendonly yes
networks: 
  redisnet:
    driver: bridge
